version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8082:8082"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 8082"
